### ISSUE TITLE
where is the code?

### ISSUE THREAD

**Issue by chaoge123456** [AhmedSalem2/ML-Leaks#1]
Hi, PhD Ahmed Salem! I have read you paper (ML-Leaks: Model and Data Independent Membership Inference Attacks and Defenses on Machine Learning Models), and this work is cool. But some details,  I can't  understand. If you can show the code, it will be nice! Thank you!

**Comment by Guyanqi** [comment]
Same question, where is the code?

**Comment by gulai22** [comment]
https://github.com/Lab41/cyphercat/tree/master/Attack_baselines/Membership_Inference

**Comment by chaoge123456** [comment]
> https://github.com/Lab41/cyphercat/tree/master/Attack_baselines/Membership_Inference
